# -*- coding: utf-8 -*-
"""Task1_ToDoList.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lUmYYE-o451dw4LtqXOyMkEX3c6ww6YT
"""

import os

TASKS_FILE = "tasks.txt"

# Load tasks from file
def load_tasks():
    if not os.path.exists(TASKS_FILE):
        return []
    with open(TASKS_FILE, "r") as f:
        tasks = [line.strip() for line in f.readlines()]
    return tasks

# Save tasks to file
def save_tasks(tasks):
    with open(TASKS_FILE, "w") as f:
        for task in tasks:
            f.write(task + "\n")

# Show tasks
def show_tasks(tasks):
    if not tasks:
        print("\nNo tasks found!\n")
    else:
        print("\nYour To-Do List:")
        for i, task in enumerate(tasks, start=1):
            print(f"{i}. {task}")
        print()

# Add a task
def add_task(tasks):
    task = input("Enter new task: ")
    tasks.append(task)
    save_tasks(tasks)
    print("✅ Task added successfully!")

# Mark a task as done
def mark_done(tasks):
    show_tasks(tasks)
    try:
        task_no = int(input("Enter task number to mark as done: "))
        tasks[task_no-1] += " ✅"
        save_tasks(tasks)
        print("🎯 Task marked as done!")
    except (ValueError, IndexError):
        print("❌ Invalid task number!")

# Delete a task
def delete_task(tasks):
    show_tasks(tasks)
    try:
        task_no = int(input("Enter task number to delete: "))
        removed = tasks.pop(task_no-1)
        save_tasks(tasks)
        print(f"🗑️ Deleted: {removed}")
    except (ValueError, IndexError):
        print("❌ Invalid task number!")

# Main program
def todo_list():
    tasks = load_tasks()
    while True:
        print("\n==== TO-DO LIST MENU ====")
        print("1. View Tasks")
        print("2. Add Task")
        print("3. Mark Task as Done")
        print("4. Delete Task")
        print("5. Exit")

        choice = input("Enter choice: ")

        if choice == "1":
            show_tasks(tasks)
        elif choice == "2":
            add_task(tasks)
        elif choice == "3":
            mark_done(tasks)
        elif choice == "4":
            delete_task(tasks)
        elif choice == "5":
            print("👋 Goodbye!")
            break
        else:
            print("❌ Invalid choice! Try again.")

todo_list()