# -*- coding: utf-8 -*-
"""Task3_RockPaperScissors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17gbbWS6vF0IIDG-QTAuZumniRCPAt6IV
"""

import random

def play_game():
    user_score = 0
    computer_score = 0

    while True:
        print("\n=== Rock-Paper-Scissors Game ===")
        print("Choices: rock, paper, scissors")
        user_choice = input("Enter your choice: ").lower()

        if user_choice not in ["rock", "paper", "scissors"]:
            print("❌ Invalid choice! Please choose rock, paper, or scissors.")
            continue

        computer_choice = random.choice(["rock", "paper", "scissors"])
        print(f"🧑 You chose: {user_choice}")
        print(f"💻 Computer chose: {computer_choice}")

        # Game Logic
        if user_choice == computer_choice:
            print("🤝 It's a Tie!")
        elif (user_choice == "rock" and computer_choice == "scissors") or \
             (user_choice == "scissors" and computer_choice == "paper") or \
             (user_choice == "paper" and computer_choice == "rock"):
            print("🎉 You Win!")
            user_score += 1
        else:
            print("😢 You Lose!")
            computer_score += 1

        # Show Scores
        print(f"Score → You: {user_score} | Computer: {computer_score}")

        # Ask to play again
        play_again = input("Do you want to play again? (yes/no): ").lower()
        if play_again != "yes":
            print("\nThanks for playing! Final Score:")
            print(f"🧑 You: {user_score} | 💻 Computer: {computer_score}")
            break

# Run the game
play_game()