# -*- coding: utf-8 -*-
"""TASK2_Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WlacUArvbbSF7HTt_ISIn5ZRsZ4_hns8
"""

# Simple Calculator - CodSoft Task 2

def calculator():
    print("=== SIMPLE CALCULATOR ===")
    print("Operations: + (Addition), - (Subtraction), * (Multiplication), / (Division)")

    try:
        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))
        op = input("Enter operation (+, -, *, /): ")

        if op == "+":
            result = num1 + num2
        elif op == "-":
            result = num1 - num2
        elif op == "*":
            result = num1 * num2
        elif op == "/":
            if num2 == 0:
                print("❌ Error: Division by zero is not allowed.")
                return
            result = num1 / num2
        else:
            print("❌ Invalid operation!")
            return

        print(f"✅ Result: {result}")

    except ValueError:
        print("❌ Invalid input! Please enter numeric values.")

# Run the calculator
calculator()
